/******************************************************************************\
 * Logic paradigm implementation in Java
 * Author: Daniel Amador Salas
 * Version: 1.0
 * Date: October 16th
\******************************************************************************/
package app.view;

public class CreateMazeView extends javax.swing.JFrame {

    /**
     * Creates new form GameView
     */
    public CreateMazeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgEditOptions = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        pnMaze = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbnAddFloor = new javax.swing.JRadioButton();
        rbnAddWasp = new javax.swing.JRadioButton();
        rbnAddSpider = new javax.swing.JRadioButton();
        rbnAddStone = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CreateMaze");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/util/MainViewTitle.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 110));

        pnMaze.setMaximumSize(new java.awt.Dimension(403, 403));
        pnMaze.setMinimumSize(new java.awt.Dimension(403, 403));
        pnMaze.setLayout(new java.awt.GridLayout(7, 7));
        getContentPane().add(pnMaze, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 403, 403));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Instrucciones");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btgEditOptions.add(rbnAddFloor);
        rbnAddFloor.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        rbnAddFloor.setForeground(new java.awt.Color(254, 254, 254));
        rbnAddFloor.setText("Add floor");
        rbnAddFloor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnAddFloorActionPerformed(evt);
            }
        });
        jPanel1.add(rbnAddFloor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btgEditOptions.add(rbnAddWasp);
        rbnAddWasp.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        rbnAddWasp.setForeground(new java.awt.Color(254, 254, 254));
        rbnAddWasp.setText("Add wasp");
        rbnAddWasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnAddWaspActionPerformed(evt);
            }
        });
        jPanel1.add(rbnAddWasp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        btgEditOptions.add(rbnAddSpider);
        rbnAddSpider.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        rbnAddSpider.setForeground(new java.awt.Color(254, 254, 254));
        rbnAddSpider.setSelected(true);
        rbnAddSpider.setText("Add Spider");
        jPanel1.add(rbnAddSpider, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        btgEditOptions.add(rbnAddStone);
        rbnAddStone.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        rbnAddStone.setForeground(new java.awt.Color(254, 254, 254));
        rbnAddStone.setText("Add stone");
        jPanel1.add(rbnAddStone, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 160, 170, -1));

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setFont(new java.awt.Font("Hack", 1, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.setToolTipText("");
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 320, 170, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/util/CreateMazeBackground.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbnAddWaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnAddWaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnAddWaspActionPerformed

    private void rbnAddFloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnAddFloorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnAddFloorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateMazeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateMazeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateMazeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateMazeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateMazeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgEditOptions;
    public javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel pnMaze;
    public javax.swing.JRadioButton rbnAddFloor;
    public javax.swing.JRadioButton rbnAddSpider;
    public javax.swing.JRadioButton rbnAddStone;
    public javax.swing.JRadioButton rbnAddWasp;
    // End of variables declaration//GEN-END:variables
}
