/******************************************************************************\
 * Logic paradigm implementation in Java
 * Author: Daniel Amador Salas
 * Version: 1.0
 * Date: October 16th
\******************************************************************************/
package app.view;

import app.controller.MainViewController;
import app.model.Cell;

public class MainView extends javax.swing.JFrame {
    private MainViewController mvController;
    public Cell[][] maze;
    public Cell wasp = null;
    public Cell spider = null;
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        mvController = new MainViewController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnCreateMaze = new javax.swing.JButton();
        btnStartGame = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainView");
        setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Phetsarath OT", 1, 52)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(254, 254, 254));
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/util/MainViewTitle.png"))); // NOI18N
        lblTitle.setToolTipText("");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -80, -1, -1));

        btnCreateMaze.setBackground(new java.awt.Color(0, 153, 153));
        btnCreateMaze.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        btnCreateMaze.setForeground(new java.awt.Color(254, 254, 254));
        btnCreateMaze.setText("Create Maze");
        btnCreateMaze.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnCreateMaze, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 570, 320, 120));

        btnStartGame.setBackground(new java.awt.Color(0, 153, 153));
        btnStartGame.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        btnStartGame.setForeground(new java.awt.Color(254, 254, 254));
        btnStartGame.setText("Start Game");
        btnStartGame.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnStartGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 440, 320, 120));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/util/MainViewBackground.jpg"))); // NOI18N
        lblBackground.setMaximumSize(new java.awt.Dimension(1280, 720));
        lblBackground.setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCreateMaze;
    public javax.swing.JButton btnStartGame;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
